Repository Clokey-dev/Clokey_iOS, pull requests merged in 2025-02, with the labels that each got.

#17 [Feature] 내 프로필 뷰 UI 수정
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Feature/Main/HeaderView.swift
  Clokey/Clokey/Sources/Feature/Main/MainView.swift
  Clokey/Clokey/Sources/Feature/Main/MainViewController.swift
  Clokey/Clokey/Sources/Feature/Main/MainViewModel.swift
  Clokey/Clokey/Sources/Feature/Main/TabBarView.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileModel.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileView.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileModel.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileView.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift
Labels: feature

#19 [Feature] Calendar 페이지 기본 기능 세팅 완료
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Resources/Assets.xcassets/test_cloth.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/test_cloth.imageset/test_cloth.png
  Clokey/Clokey/Sources/Common/Components/CustomButton.swift
  Clokey/Clokey/Sources/Common/Components/CustomButtonTextField.swift
  Clokey/Clokey/Sources/Common/Components/CustomCategoryModel.swift
  Clokey/Clokey/Sources/Common/Components/CustomCollectionViewCell.swift
  Clokey/Clokey/Sources/Common/Components/CustomNavigationBar.swift
  Clokey/Clokey/Sources/Common/Components/CustomSearchField.swift
  Clokey/Clokey/Sources/Common/Components/CustomSortDropdownView.swift
  Clokey/Clokey/Sources/Common/Components/CustomTextField.swift
  Clokey/Clokey/Sources/Common/Components/CustomTotalSegmentView.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/ContentInputView.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/Photo/CustomGalleryViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/Photo/ImageCollectionViewCell.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/Photo/PhotoEditViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/PhotoTagView.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/RecordOOTDView.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/RecordOOTDViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/TagCloth/TagClothModel.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/TagCloth/TagClothView.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/TagCloth/TagClothViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CalendarView.swift
  Clokey/Clokey/Sources/Feature/Calendar/CalendarViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/Calendar/CalendarCell.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/Calendar/CalendarHelper.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/Calendar/CalendarModel.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/Calendar/CalendarView.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/Calendar/CalendarViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/CalendarDetailView.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/CalendarDetailViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/UploadModalView.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/UploadModalViewController.swift
  Clokey/Clokey/Sources/Feature/ViewController.swift
Labels: feature

#22 [Feature] 캘린더 월별 API 연결
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Application/SceneDelegate.swift
  Clokey/Clokey/Clokey.entitlements
  Clokey/Clokey/Resources/Assets.xcassets/side_bar.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/side_bar.imageset/side_bar.png
  Clokey/Clokey/Sources/Common/Components/CustomTextField.swift
  Clokey/Clokey/Sources/Common/Components/CustomTotalSegmentView.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/ContentInputView.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/Photo/CustomGalleryViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/Photo/PhotoEditViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/PhotoTagView.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/RecordOOTDView.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/RecordOOTDViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/Calendar/CalendarCell.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/Calendar/CalendarView.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/Calendar/CalendarViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/CalendarDetailView.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/CalendarDetailViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/CalendarImageCell.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/CalendarCommentView.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/CalendarCommentViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/Comment.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/CommentCell.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/CustomActionSheetViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/LikeUser/LikeListViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/LikeUser/LikeUserCell.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/LikeUser/LikeUserModel.swift
  Clokey/Clokey/Sources/Feature/Login/LoginViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileView.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Services/KakaoAuthService.swift
  Clokey/Clokey/Sources/Feature/Services/KeychainHelper.swift
  Clokey/Clokey/Sources/Network/Clothes/Endpoints/ClothesEndpoint.swift
  Clokey/Clokey/Sources/Network/Clothes/Request/AddClothesRequestDTO.swift
  Clokey/Clokey/Sources/Network/Clothes/Response/InquiryClothesDetailResponseDTO.swift
  Clokey/Clokey/Sources/Network/Clothes/Service/ClothesService.swift
  Clokey/Clokey/Sources/Network/Common/Domain.swift
  Clokey/Clokey/Sources/Network/Common/Extensions/NetworkManager+Extension.swift
  Clokey/Clokey/Sources/Network/Common/NetworkError.swift
  Clokey/Clokey/Sources/Network/Common/Plugins/AccessTokenPlugin.swift
  Clokey/Clokey/Sources/Network/Common/Plugins/CookiePlugin.swift
  Clokey/Clokey/Sources/Network/Common/Protocols/NetworkManager+Protocol.swift
  Clokey/Clokey/Sources/Network/Common/Response/CommonReponseDTOs.swift
  Clokey/Clokey/Sources/Network/history/Endpoints/HistoryEndpoint.swift
  Clokey/Clokey/Sources/Network/history/Request/HistoryRequestDTO.swift
  Clokey/Clokey/Sources/Network/history/Response/HistoryResponseDTO.swift
  Clokey/Clokey/Sources/Network/history/Service/HistoryService.swift
  Clokey/Clokey/Sources/Network/home/Endpoints/HomeEndPoint.swift
  Clokey/Clokey/Sources/Network/home/Response/OneYearAgoHistoriesResponseDTO.swift
  Clokey/Clokey/Sources/Network/home/Service/HomeService.swift
  Clokey/Clokey/Sources/Network/members/Endpoints/MembersEndpoint.swift
  Clokey/Clokey/Sources/Network/members/Request/MembersInfoRequestDTO.swift
  Clokey/Clokey/Sources/Network/members/Request/MembersLoginRequestDTO.swift
  Clokey/Clokey/Sources/Network/members/Response/MembersInfoResponseDTO.swift
  Clokey/Clokey/Sources/Network/members/Response/MembersLoginResponseDTO.swift
  Clokey/Clokey/Sources/Network/members/Service/MembersService.swift
  Clokey/Clokey/Supporting Files/Info.plist
Labels: feature

#24 [Feature] 홈 뷰 수정
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Feature/Home/Cells 2/UpdateFriendCalendarCollectionViewCell.swift
  Clokey/Clokey/Sources/Feature/Home/Cells 2/UpdateFriendClothesCollectionViewCell.swift
  Clokey/Clokey/Sources/Feature/Home/Cells 2/WeatherClothesCollectionViewCell.swift
  Clokey/Clokey/Sources/Feature/Home/EmptyStackView.swift
  Clokey/Clokey/Sources/Feature/Home/Models/UpdateFriendClothesModel.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/HomeViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/Main/NewsViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/More/UpdateFriendCalendarViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/More/UpdateFriendClothesViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickNothingViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/Popup/PickPopUpViewController.swift
  Clokey/Clokey/Sources/Feature/Home/Views/HomeView.swift
  Clokey/Clokey/Sources/Feature/Home/Views/NewsViews/More/UpdateFriendCalendarView.swift
  Clokey/Clokey/Sources/Feature/Home/Views/NewsViews/More/UpdateFriendClothesView.swift
  Clokey/Clokey/Sources/Feature/Home/Views/PickViews/PickNothingView.swift
  Clokey/Clokey/Sources/Feature/Home/Views/PickViews/PickView.swift
  Clokey/Clokey/Sources/Feature/Home/Views/PickViews/Popup/PickPopUpView.swift
Labels: feature

#21 [Feature] 메인 VC 및 SceneDelegate 수정
  Clokey/Clokey/Application/SceneDelegate.swift
  Clokey/Clokey/Sources/Feature/Main/MainView.swift
  Clokey/Clokey/Sources/Feature/Main/MainViewController.swift
Labels: feature

#25 [Feature] 프로필 뷰 UI 수정 및 추가
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Resources/Assets.xcassets/cry_icon.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/cry_icon.imageset/Crying Face.png
  Clokey/Clokey/Resources/Assets.xcassets/kakao_icon.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/kakao_icon.imageset/Ellipse 51.png
  Clokey/Clokey/Sources/Feature/Profile/EditProfile/CustomBottomSheetViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/EditProfile/EditProfileView.swift
  Clokey/Clokey/Sources/Feature/Profile/EditProfile/EditProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/FollowList/FollowListViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/FollowList/FollowerUserCell.swift
  Clokey/Clokey/Sources/Feature/Profile/FollowList/FollowerUserModel.swift
  Clokey/Clokey/Sources/Feature/Profile/FollowList/FollowingUserCell.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileView.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/DeleteAccountView.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/DeleteAccountViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/SettingView.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/SettingViewController.swift
Labels: feature

#38 [Feature] 자동 로그인 로직 추가 및 재발급 토큰 추가
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Application/SceneDelegate.swift
  Clokey/Clokey/Resources/Base.lproj/LaunchScreen.storyboard
  Clokey/Clokey/Resources/Lottie/Onboarding_no.json
  Clokey/Clokey/Resources/Lottie/Onboarding_yes.json
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/ContentInputView.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/TagCloth/TagClothView.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/TagCloth/TagClothViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/UploadModalView.swift
  Clokey/Clokey/Sources/Feature/Login/LoginViewController.swift
  Clokey/Clokey/Sources/Feature/Main/MainView.swift
  Clokey/Clokey/Sources/Feature/Main/MainViewController.swift
  Clokey/Clokey/Sources/Feature/Onboarding/LottieViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/SettingView.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/SettingViewController.swift
  Clokey/Clokey/Sources/Feature/Services/JWTHelper.swift
  Clokey/Clokey/Sources/Feature/Services/TokenManager.swift
  Clokey/Clokey/Sources/Network/Clothes/Response/InquiryClothesDetailResponseDTO.swift
  Clokey/Clokey/Sources/Network/Clothes/Service/ClothesService.swift
  Clokey/Clokey/Sources/Network/Common/Plugins/TokenRefreshPlugin.swift
  Clokey/Clokey/Sources/Network/categories/Service/CategoriesService.swift
  Clokey/Clokey/Sources/Network/history/Service/HistoryService.swift
  Clokey/Clokey/Sources/Network/members/Endpoints/MembersEndpoint.swift
  Clokey/Clokey/Sources/Network/members/Request/MembersLoginRequestDTO.swift
  Clokey/Clokey/Sources/Network/members/Response/MembersLoginResponseDTO.swift
  Clokey/Clokey/Sources/Network/members/Service/MembersService.swift
  Clokey/Clokey/Sources/Network/search/Service/SearchService.swift
Labels: bug, feature

#39 [Feature] 홈(PICK, 소식) API 연결
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddClothViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddClothesView.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Category/AddCategoryHeaderView1.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Category/AddCategoryModel1.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Category/AddCategoryView1.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Category/AddCategoryViewCollectionViewCell1.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Category/AddCategoryViewController1.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Category/CategoryHeaderView.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Category/CategoryModel.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Category/CategoryView.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Category/CategoryViewCollectionViewCell.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Category/CategoryViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Popup/AddClothView.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Popup/PopupView.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Popup/PopupViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Temperature/Slider.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Temperature/WeatherChooseViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Thick/ThickSlider.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Thick/ThickViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddClothing/AddClothingViewController.swift
  Clokey/Clokey/Sources/Feature/AddProfile/AddProfileView.swift
  Clokey/Clokey/Sources/Feature/AddProfile/AddProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Agreement/AgreementViewController.swift
  Clokey/Clokey/Sources/Feature/Home/Cells/UpdateFriendCalendarCollectionViewCell.swift
  Clokey/Clokey/Sources/Feature/Home/Cells/UpdateFriendClothesCollectionViewCell.swift
  Clokey/Clokey/Sources/Feature/Home/Models/NewsImageModel.swift
  Clokey/Clokey/Sources/Feature/Home/Models/RecommandNewsSlideModel.swift
  Clokey/Clokey/Sources/Feature/Home/Models/UpdateFriendCalendarModel.swift
  Clokey/Clokey/Sources/Feature/Home/Models/UpdateFriendClothesModel.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/HomeViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/Main/ImageViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/Main/NewsViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/More/UpdateFriendCalendarViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/More/UpdateFriendClothesViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift
  Clokey/Clokey/Sources/Feature/Home/Views/HomeView.swift
  Clokey/Clokey/Sources/Feature/Home/Views/NewsViews/Main/ImageView.swift
  Clokey/Clokey/Sources/Feature/Home/Views/NewsViews/Main/NewsView.swift
  Clokey/Clokey/Sources/Feature/Home/Views/NewsViews/More/UpdateFriendCalendarView.swift
  Clokey/Clokey/Sources/Feature/Home/Views/NewsViews/More/UpdateFriendClothesView.swift
  Clokey/Clokey/Sources/Feature/Home/Views/PickViews/PickView.swift
  Clokey/Clokey/Sources/Network/Clothes/Endpoints/ClothesEndpoint.swift
  Clokey/Clokey/Sources/Network/Clothes/Request/AddClothesRequestDTO.swift
  Clokey/Clokey/Sources/Network/Clothes/Response/InquiryClothesDetailResponseDTO.swift
  Clokey/Clokey/Sources/Network/Clothes/Service/ClothesService.swift
  Clokey/Clokey/Sources/Network/home/Endpoints/HomeEndPoint.swift
  Clokey/Clokey/Sources/Network/home/Response/OneYearAgoHistoriesResponseDTO.swift
  Clokey/Clokey/Sources/Network/home/Service/HomeService.swift
Labels: bug, feature

#41 [Fix] 디바이스 토큰 버그 수정 및 댓글 닉네임 버그 수정
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Application/AppDelegate.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/Calendar/CalendarViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/CalendarDetailViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/CalendarCommentView.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/CalendarCommentViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/Comment.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/HomeViewController.swift
  Clokey/Clokey/Sources/Feature/Login/LoginViewController.swift
  Clokey/Clokey/Sources/Network/history/Response/HistoryResponseDTO.swift
  Clokey/Clokey/Sources/Network/notification/Response/NotificationResponseDTO.swift
Labels: hotfix

#42 [Feature] 홈 및 프로필 네트워크 설정
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Resources/Config.xcconfig
  Clokey/Clokey/Sources/Feature/AddProfile/AddProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/Main/NewsViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/EditProfile/EditProfileView.swift
  Clokey/Clokey/Sources/Feature/Profile/EditProfile/EditProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/FollowList/FollowListViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileView.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileViewModel.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/SettingView.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/SettingViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileModel.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileView.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift
  Clokey/Clokey/Sources/Network/members/Endpoints/MembersEndpoint.swift
  Clokey/Clokey/Sources/Network/members/Request/MembersInfoRequestDTO.swift
  Clokey/Clokey/Sources/Network/members/Response/MembersInfoResponseDTO.swift
  Clokey/Clokey/Sources/Network/members/Service/MembersService.swift
Labels: bug, feature

#43 [Feature] 알림 읽음 처리 API 연동 완료
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Feature/Nofitication/Model/NotificationViewModel.swift
  Clokey/Clokey/Sources/Feature/Nofitication/VIews/NotificationView.swift
  Clokey/Clokey/Sources/Feature/Nofitication/ViewControllers/NotificationViewController.swift
  Clokey/Clokey/Sources/Feature/Search/Model/SearchResultModel.swift
  Clokey/Clokey/Sources/Feature/Search/Model/UserModel.swift
  Clokey/Clokey/Sources/Feature/Search/ViewControllers/SearchResultViewController.swift
  Clokey/Clokey/Sources/Feature/Search/ViewControllers/SearchViewController.swift
  Clokey/Clokey/Sources/Network/notification/Endpoints/NotificationEndpoints.swift
  Clokey/Clokey/Sources/Network/notification/Response/NotificationResponseDTO.swift
  Clokey/Clokey/Sources/Network/notification/Service/NotificationService.swift
  Clokey/Clokey/Sources/Network/search/Endpoints/SearchEndpoint.swift
  Clokey/Clokey/Sources/Network/search/Response/SearchResponseDTO.swift
Labels: feature

#44 [Feature] 프로필에서 캘린더 연결 완료 및 상단 컴포넌트 버그 수정
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/Calendar/CalendarViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/CalendarDetailView.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/CalendarCommentViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileView.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileViewController.swift
Labels: bug, feature

#45 [Feature] 홈 페이지에서 세부 기록 페이지 띄우기 및 댓글 알림
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/Calendar/CalendarViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/Calendar/FriendsCalendarDetailViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/CalendarDetailView.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/CalendarCommentViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/CommentCell.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/FriendsCalendarDetailViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/Main/NewsViewController.swift
  Clokey/Clokey/Sources/Network/notification/Response/NotificationResponseDTO.swift
  Clokey/Clokey/Sources/Network/notification/Service/NotificationService.swift
Labels: bug, feature

#47 [Feature] 홈 및 프로필 네트워크 수정 및 추가
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Category/CategoryModel.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Popup/PopupView.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift
  Clokey/Clokey/Sources/Feature/Home/Views/PickViews/Popup/PickPopUpView.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileView.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/MyFollowList/MyFollowListViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/MyFollowList/MyFollowerUserCell.swift
  Clokey/Clokey/Sources/Feature/Profile/MyFollowList/MyFollowerUserModel.swift
  Clokey/Clokey/Sources/Feature/Profile/MyFollowList/MyFollowingUserCell.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/SettingViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/YourFollowList/YourFollowListViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/YourFollowList/YourFollowerUserCell.swift
  Clokey/Clokey/Sources/Feature/Profile/YourFollowList/YourFollowerUserModel.swift
  Clokey/Clokey/Sources/Feature/Profile/YourFollowList/YourFollowingUserCell.swift
  Clokey/Clokey/Sources/Network/Clothes/Endpoints/ClothesEndpoint.swift
  Clokey/Clokey/Sources/Network/Clothes/Response/InquiryClothesDetailResponseDTO.swift
  Clokey/Clokey/Sources/Network/Clothes/Service/ClothesService.swift
  Clokey/Clokey/Sources/Network/members/Endpoints/MembersEndpoint.swift
  Clokey/Clokey/Sources/Network/members/Request/MembersInfoRequestDTO.swift
  Clokey/Clokey/Sources/Network/members/Response/MembersInfoResponseDTO.swift
  Clokey/Clokey/Sources/Network/members/Service/MembersService.swift
Labels: bug, feature

#46 [Feature] Closet 부분 UI, 기능 구현 및 API 연동
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Resources/Assets.xcassets/New Folder/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/New Folder/bannerimage1.imageset/Cloth Donation.png
  Clokey/Clokey/Resources/Assets.xcassets/New Folder/bannerimage1.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/New Folder/bannerimage2.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/New Folder/bannerimage2.imageset/Lockers.png
  Clokey/Clokey/Resources/Assets.xcassets/New Folder/empty_icon.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/New Folder/empty_icon.imageset/Frame 1892.png
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/ArrangeClosetBannerView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/ArrangeClosetView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/ArrangeClosetViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/SmartSummationBannerView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/SmartSummationModel.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/SmartSummationView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/SmartSummationViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/ClosetCollectionViewCell.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/ClosetModel.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/ClosetView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/ClosetViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/EmptyStateView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/ClosetPopUpView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/ClosetPopUpViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/PopUpDropdownView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/PopUpDropdownViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/DisplayAll/DisplayAllView.swift
  Clokey/Clokey/Sources/Feature/Closet/DisplayAll/DisplayAllViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerCollectionViewCell.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerEditView.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerEditViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerInfoView.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerInfoViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerModel.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerView.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/FolderDropdownView.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/FolderDropdownViewController.swift
  Clokey/Clokey/Sources/Network/Clothes/Endpoints/ClothesEndpoint.swift
  Clokey/Clokey/Sources/Network/Clothes/Response/InquiryClothesDetailResponseDTO.swift
  Clokey/Clokey/Sources/Network/Clothes/Service/ClothesService.swift
  Clokey/Clokey/Sources/Network/folder/Endpoints/FolderEndpoint.swift
  Clokey/Clokey/Sources/Network/folder/Request/FolderRequestDTO.swift
  Clokey/Clokey/Sources/Network/folder/Response/FolderResponseDTO.swift
  Clokey/Clokey/Sources/Network/folder/Service/FolderService.swift
Labels: feature

#48 [Fix] 프로필 수정 버그 해결
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddClothViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddImage/LastAddViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Category/CategoryViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Temperature/WeatherChooseViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Thick/ThickViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/Main/NewsViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/More/UpdateFriendCalendarViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/More/UpdateFriendClothesViewController.swift
  Clokey/Clokey/Sources/Feature/Main/MainViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/EditProfile/EditProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileView.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/MyFollowList/MyFollowListViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowCalendarViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileView.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/YourFollowList/YourFollowListViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/YourFollowList/YourFollowerUserCell.swift
  Clokey/Clokey/Sources/Network/members/Response/MembersInfoResponseDTO.swift
Labels: bug, feature

#49 [Feature] develop과 merge
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/CalendarDetailViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/HomeViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/Main/NewsViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift
  Clokey/Clokey/Sources/Feature/Nofitication/Model/NotificationType.swift
  Clokey/Clokey/Sources/Feature/Nofitication/Model/NotificationViewModel.swift
  Clokey/Clokey/Sources/Feature/Nofitication/VIews/NotificationCell.swift
  Clokey/Clokey/Sources/Feature/Nofitication/VIews/NotificationView.swift
  Clokey/Clokey/Sources/Feature/Nofitication/ViewControllers/NotificationViewController.swift
  Clokey/Clokey/Sources/Feature/Search/Model/SearchManager.swift
  Clokey/Clokey/Sources/Feature/Search/Model/UserCell.swift
  Clokey/Clokey/Sources/Feature/Search/ViewControllers/SearchResultViewController.swift
  Clokey/Clokey/Sources/Feature/Search/ViewControllers/SearchViewController.swift
  Clokey/Clokey/Sources/Feature/Search/view/SearchView.swift
Labels: feature

#50 [Feature] Clokey의 기본적인 기능 구현
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Application/AppDelegate.swift
  Clokey/Clokey/Application/SceneDelegate.swift
  Clokey/Clokey/Sources/Common/Components/Category/AddCategoryViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/Photo/CustomGalleryViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/Photo/PhotoEditViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/RecordOOTDView.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/RecordOOTDViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/TagCloth/TagClothViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/Calendar/CalendarViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/CalendarDetailViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/FriendsCalendarDetailViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/LikeUser/LikeListViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/LikeUser/LikeUserCell.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/LikeUser/LikeUserModel.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/Main/NewsViewController.swift
  Clokey/Clokey/Sources/Feature/Home/Views/NewsViews/Main/NewsView.swift
  Clokey/Clokey/Sources/Feature/Profile/MyFollowList/MyFollowerUserCell.swift
  Clokey/Clokey/Sources/Feature/Profile/MyFollowList/MyFollowingUserCell.swift
  Clokey/Clokey/Sources/Network/history/Response/HistoryResponseDTO.swift
Labels: bug, feature

#51 [Feature] popup부분 API 연동 및 기능 구현
  Clokey/Clokey/Resources/Assets.xcassets/2D ICONS/dot3_icon.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/2D ICONS/dot3_icon.imageset/dot3_icon.png
  Clokey/Clokey/Resources/Assets.xcassets/2D ICONS/dot3_icon.imageset/더보기 (3).png
  Clokey/Clokey/Resources/Assets.xcassets/Compoenets_icon/erase_icon.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/Compoenets_icon/erase_icon.imageset/erase_icon.png
  Clokey/Clokey/Resources/Assets.xcassets/Compoenets_icon/erase_icon.imageset/지우기 (1).png
  Clokey/Clokey/Resources/Assets.xcassets/lock_off.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/lock_off.imageset/Group 1707481830.png
  Clokey/Clokey/Resources/Assets.xcassets/lock_off.imageset/lock_off.png
  Clokey/Clokey/Resources/Assets.xcassets/lock_on.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/lock_on.imageset/KakaoTalk_Photo_2025-02-20-07-46-22.png
  Clokey/Clokey/Resources/Assets.xcassets/lock_on.imageset/lock_on.png
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/ClosetViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/ClosetPopUpView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/ClosetPopUpViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/DisplayAll/DisplayAllViewController.swift
Labels: feature

#52 [Feature] 소식-옷장 팝업뷰 추가, 카테고리 분류 시 인디케이터 생성
  Clokey/Clokey/Application/SceneDelegate.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddClothViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Popup/PopupViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Success/SuccessViewController.swift
  Clokey/Clokey/Sources/Feature/AddProfile/AddProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/Main/NewsViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift
Labels: feature

#54 [Featrue] 앱 아이콘 추가 및 기록 상단바 버그 수정
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  Clokey/Clokey/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  Clokey/Clokey/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  Clokey/Clokey/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  Clokey/Clokey/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  Clokey/Clokey/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  Clokey/Clokey/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  Clokey/Clokey/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  Clokey/Clokey/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  Clokey/Clokey/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  Clokey/Clokey/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  Clokey/Clokey/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Clokey/Clokey/Sources/Common/Components/CustomNavigationBar.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/CalendarDetailViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/FriendsCalendarDetailViewController.swift
  Clokey/Clokey/Supporting Files/Info.plist
Labels: bug, feature

#56 [Feature] 스마트 요약 쪽 API 연결
  Clokey/Clokey/Sources/Common/Components/Category/AddCategoryHeaderView.swift
  Clokey/Clokey/Sources/Common/Components/Category/AddCategoryViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/SmartSummationView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/SmartSummationViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/ClosetView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/ClosetViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/ClosetPopUpViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/PopUpDropdownViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/DisplayAll/DisplayAllViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerInfoView.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerViewController.swift
  Clokey/Clokey/Sources/Network/Clothes/Response/InquiryClothesDetailResponseDTO.swift
Labels: bug, feature

#58 [Fix] 팔로우/팔로잉 목록조회 수정
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift
  Clokey/Clokey/Sources/Feature/Home/Views/PickViews/PickView.swift
  Clokey/Clokey/Sources/Feature/Main/MainViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/MyFollowList/MyFollowListViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/MyFollowList/MyFollowerUserCell.swift
  Clokey/Clokey/Sources/Feature/Profile/MyFollowList/MyFollowingUserCell.swift
  Clokey/Clokey/Sources/Feature/Profile/YourFollowList/YourFollowListViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/YourFollowList/YourFollowerUserCell.swift
  Clokey/Clokey/Sources/Feature/Profile/YourFollowList/YourFollowerUserModel.swift
  Clokey/Clokey/Sources/Feature/Profile/YourFollowList/YourFollowingUserCell.swift
  Clokey/Clokey/Sources/Network/members/Response/MembersInfoResponseDTO.swift
Labels: bug, feature

#60 [Feature] CloserPopUpView 관련 로직 수정 및 기타 버그 수정
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Common/Components/Category/AddCategoryView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/ClosetView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/ClosetViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/ClosetPopUpView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/ClosetPopUpViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/PopUpDropdownViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/DisplayAll/DisplayAllView.swift
  Clokey/Clokey/Sources/Feature/Closet/DisplayAll/DisplayAllViewController.swift
  Clokey/Clokey/Sources/Network/Clothes/Service/ClothesService.swift
Labels: bug, feature

#62 [Feature] 캘린더 기록하기 버그 수정 및 상단바 수정
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/ContentInputView.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/PhotoTagView.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/RecordOOTDViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/CalendarDetailView.swift
  Clokey/Clokey/Sources/Feature/Closet/DisplayAll/DisplayAllViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift
  Clokey/Clokey/Sources/Network/members/Response/MembersLoginResponseDTO.swift
Labels: bug, feature

#63 [FIX] 팔로우 목록 조회 새로고침 수정 및 프로필 설정 뷰 수정
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Resources/Assets.xcassets/2D ICONS/dot3_icon.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/Compoenets_icon/erase_icon.imageset/Contents.json
  Clokey/Clokey/Sources/Feature/AddProfile/AddProfileView.swift
  Clokey/Clokey/Sources/Feature/AddProfile/AddProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/More/UpdateFriendCalendarViewController.swift
  Clokey/Clokey/Sources/Feature/Home/Views/NewsViews/Main/NewsView.swift
  Clokey/Clokey/Sources/Feature/Profile/EditProfile/CustomBottomSheetViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/EditProfile/EditProfileView.swift
  Clokey/Clokey/Sources/Feature/Profile/EditProfile/EditProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileView.swift
  Clokey/Clokey/Sources/Feature/Profile/MyFollowList/MyFollowListViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileView.swift
  Clokey/Clokey/Sources/Feature/Profile/YourFollowList/YourFollowListViewController.swift
Labels: bug

#64 [FIX] 내 옷장 새로고침 추가
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Resources/Assets.xcassets/2D ICONS/dot3_icon.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/Compoenets_icon/erase_icon.imageset/Contents.json
  Clokey/Clokey/Sources/Feature/Closet/DisplayAll/DisplayAllViewController.swift
Labels: bug

#65 [FIX] 팝업창 수정
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/Main/NewsViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift
Labels: bug

#66 [Feature] 스마트요약 구현
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Resources/Assets.xcassets/2D ICONS/front_icon.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/2D ICONS/front_icon.imageset/Vector (3).png
  Clokey/Clokey/Sources/Common/Components/Category/AddCategoryViewCollectionViewCell.swift
  Clokey/Clokey/Sources/Common/Components/Category/AddCategoryViewController.swift
  Clokey/Clokey/Sources/Common/Components/CustomCollectionViewCell.swift
  Clokey/Clokey/Sources/Common/Components/CustomSortDropdownView.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddClothesView.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Success/SuccessView.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Temperature/Slider.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Temperature/WeatherChooseViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Thick/ThickSlider.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Thick/ThickViewController.swift
  Clokey/Clokey/Sources/Feature/Agreement/AgreementCell.swift
  Clokey/Clokey/Sources/Feature/Agreement/AgreementDetailViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/Photo/PhotoEditViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/RecordOOTDViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/TagCloth/TagClothView.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/TagCloth/TagClothViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/CalendarCommentView.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/CommentCell.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/LikeUser/LikeListViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/LikeUser/LikeUserCell.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/tagClothList/RecordTagClothViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/SmartSummationView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/SmartSummationViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/ClosetCollectionViewCell.swift
  Clokey/Clokey/Sources/Feature/Closet/DisplayAll/DisplayAllView.swift
  Clokey/Clokey/Sources/Feature/Closet/DisplayAll/DisplayAllViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerEditView.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerEditViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerViewController.swift
  Clokey/Clokey/Sources/Feature/Home/Views/PickViews/Popup/PickPopUpView.swift
  Clokey/Clokey/Sources/Feature/Nofitication/VIews/NotificationView.swift
  Clokey/Clokey/Sources/Feature/Profile/MyFollowList/MyFollowerUserCell.swift
  Clokey/Clokey/Sources/Feature/Profile/MyFollowList/MyFollowingUserCell.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/DeleteAccountView.swift
  Clokey/Clokey/Sources/Feature/Search/Model/UserCell.swift
  Clokey/Clokey/Sources/Feature/Search/view/SearchResultView.swift
  Clokey/Clokey/Sources/Feature/Search/view/SearchView.swift
  Clokey/Clokey/Sources/Feature/ViewController.swift
  Clokey/Clokey/Sources/Network/search/Endpoints/SearchEndpoint.swift
  Clokey/Clokey/Sources/Network/search/Service/SearchService.swift
Labels: feature

#67 [Feature] 문의 사항 버튼 및 TestFlight 설정
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Feature/Profile/Settings/SettingViewController.swift
  Clokey/Clokey/Supporting Files/Info.plist
Labels: feature

#68 [FIX] 업데이트 캘린더 소식 수정
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/More/UpdateFriendCalendarViewController.swift
Labels: bug, feature

#69 [FIX] 뒤로가기 수정 및 팝업창 수정
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddClothViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/Main/NewsViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift
  Clokey/Clokey/Sources/Feature/Main/MainViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift
Labels: bug, feature

#70 [FIX] 슬라이드 제스처 및 로딩 창 생성
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddClothViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/PopUpDropdownViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/HomeViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/Main/NewsViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift
  Clokey/Clokey/Sources/Feature/Main/MainViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift
  Clokey/Clokey/Sources/Network/Clothes/Endpoints/ClothesEndpoint.swift
  Clokey/Clokey/Sources/Network/Clothes/Request/AddClothesRequestDTO.swift
  Clokey/Clokey/Sources/Network/Clothes/Response/InquiryClothesDetailResponseDTO.swift
  Clokey/Clokey/Sources/Network/Clothes/Service/ClothesService.swift
Labels: bug

#71 [Fix] 카테고리 및 달력 UI 버그 수정
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Common/Components/Category/AddCategoryView.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/Calendar/CalendarCell.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/Calendar/CalendarView.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/HomeViewController.swift
Labels: bug

#72 [FIX] PICK 네트워크 불러오는 과정에서의 뷰 수정
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift
Labels: bug

#73 [FIX] Pick 날씨 불러오기 수정
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddClothViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/HomeViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift
Labels: bug
