Repository Clokey-dev/Clokey_iOS, pull requests merged in 2025-03, with the labels that each got.

#79 [Feature] 옷 수정하기
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddClothViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddImage/LastAddViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Category/CategoryViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Popup/PopupViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Success/SuccessView.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Temperature/WeatherChooseViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Thick/ThickViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/ClosetViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/PopUpDropdownViewController.swift
  Clokey/Clokey/Sources/Network/Clothes/Endpoints/ClothesEndpoint.swift
  Clokey/Clokey/Sources/Network/Clothes/Service/ClothesService.swift
Labels: feature

#77 [Feature] 신고/차단 UI 추가 및 알림 버그 수정
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Application/AppDelegate.swift
  Clokey/Clokey/Application/SceneDelegate.swift
  Clokey/Clokey/Resources/Assets.xcassets/ActionSheet/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/ActionSheet/block_icon.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/ActionSheet/block_icon.imageset/block_icon.png
  Clokey/Clokey/Resources/Assets.xcassets/ActionSheet/delete_icon.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/ActionSheet/delete_icon.imageset/delete_icon.png
  Clokey/Clokey/Resources/Assets.xcassets/ActionSheet/edit_icon.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/ActionSheet/edit_icon.imageset/edit_icon.png
  Clokey/Clokey/Resources/Assets.xcassets/ActionSheet/report_icon.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/ActionSheet/report_icon.imageset/report_icon.png
  Clokey/Clokey/Resources/Assets.xcassets/banner/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/banner/bannerimage1.imageset/Cloth Donation.png
  Clokey/Clokey/Resources/Assets.xcassets/banner/bannerimage1.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/banner/bannerimage2.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/banner/bannerimage2.imageset/Lockers.png
  Clokey/Clokey/Resources/Assets.xcassets/banner/empty_icon.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/banner/empty_icon.imageset/Frame 1892.png
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/CustomActionSheetViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/FriendsCalendarDetailViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/SettingViewController.swift
Labels: feature

#82 [Fix] 신고하기/차단하기 액션 시트 파일 오류 수정 및 댓글 신고 기능 UI 추가
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/CalendarCommentViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/Comment.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/CommentCell.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/FriendsActionSheetViewController.swift
Labels: hotfix, feature

#85 [Feature] 설정 뷰 계정 탭 추가
  Clokey/Clokey/Sources/Common/Components/Category/AddCategoryViewController.swift
  Clokey/Clokey/Sources/Common/Components/CustomSearchField.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Category/CategoryViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Temperature/Slider.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/TagCloth/TagClothViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/CalendarDetailView.swift
  Clokey/Clokey/Sources/Feature/Profile/EditProfile/EditProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/SettingView.swift
Labels: feature

#88 [Fix] 새로 수정된 뷰 수정 및 공통 네비게이션바로 수정
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddClothViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddClothesView.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddImage/LastAddViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddImage/lastAddView.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Temperature/Slider.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Temperature/WeatherChooseViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Thick/ThickViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/HomeViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/Main/NewsViewController.swift
  Clokey/Clokey/Sources/Feature/Home/Views/HomeView.swift
  Clokey/Clokey/Sources/Feature/Home/Views/NewsViews/Main/NewsView.swift
  Clokey/Clokey/Sources/Feature/Home/Views/NewsViews/More/UpdateFriendCalendarView.swift
  Clokey/Clokey/Sources/Feature/Home/Views/PickViews/PickView.swift
  Clokey/Clokey/Sources/Feature/Home/Views/PickViews/Popup/PickPopUpView.swift
  Clokey/Clokey/Sources/Feature/Profile/EditProfile/CustomBottomSheetViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/EditProfile/EditProfileView.swift
  Clokey/Clokey/Sources/Feature/Profile/EditProfile/EditProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileView.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileView.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift
Labels: bug, feature

#92 [Feature] WeatherKit 추가
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Clokey.entitlements
Labels: feature

#93 [Bug] 옷장 속 버그 수정 1차
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/ArrangeClosetViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/SmartSummationView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/ClosetViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerView.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerViewController.swift
  Clokey/Clokey/Sources/Feature/Home/Views/NewsViews/Main/NewsView.swift
Labels: bug

#94 [Feature] 1차 TestFlight 버전 업로드
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Supporting Files/Info.plist
Labels: feature

#95 [Fix] 대댓글 알림 추가 및 옷장 세부 세그먼트 버튼 색 변경
  Clokey/Clokey/Sources/Common/Components/CustomTotalSegmentView.swift
  Clokey/Clokey/Sources/Common/Components/Report/AccountReportView.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/CalendarDetailViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/CalendarCommentViewController.swift
Labels: bug

#96 [Fix] 새로 수정된 프로필 뷰 수정
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Common/Components/CustomNavigationBar.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddClothViewController.swift
  Clokey/Clokey/Sources/Feature/AddProfile/AddProfileView.swift
  Clokey/Clokey/Sources/Feature/AddProfile/AddProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift
  Clokey/Clokey/Sources/Feature/Main/MainViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/EditProfile/EditProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileView.swift
  Clokey/Clokey/Sources/Feature/Profile/MyFollowList/MyFollowListViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileView.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/YourFollowList/YourFollowListViewController.swift
Labels: bug, feature

#97 [Fix] 새로 수정 페이지 뷰 수정
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Common/Components/Report/AccountReportCompleteViewController.swift
  Clokey/Clokey/Sources/Common/Components/Report/AccountReportView.swift
  Clokey/Clokey/Sources/Common/Components/Report/AccountReportViewController.swift
  Clokey/Clokey/Sources/Common/Components/Report/ReportSuccessView.swift
  Clokey/Clokey/Sources/Common/Components/Report/ReportSuccessViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Popup/PopupView.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Popup/PopupViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/SettingView.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/SettingViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileView.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift
Labels: bug, feature

#98 [Fix] report 파일 수정
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Common/Components/Report/AccountReportCompleteView.swift
  Clokey/Clokey/Sources/Common/Components/Report/AccountReportCompleteViewController.swift
  Clokey/Clokey/Sources/Common/Components/Report/AccountReportView.swift
  Clokey/Clokey/Sources/Common/Components/Report/AccountReportViewController.swift
  Clokey/Clokey/Sources/Common/Components/Report/ReportReason.swift
  Clokey/Clokey/Sources/Common/Components/Report/ReportReasonView.swift
Labels: bug, in progress

#100 [Feature] 좋아요한 게시물 뷰 구현
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddClothViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddClothesView.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/CalendarDetailView.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/CalendarDetailViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/FriendsCalendarDetailViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/Main/NewsViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/LikeHistoryCell.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/LikeHistoryManager.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/LikeHistoryView.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/LikeHistoryViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/LikeHistoryViewDelegate.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/SettingViewController.swift
  Clokey/Clokey/Sources/Feature/Search/Model/SearchManager.swift
  Clokey/Clokey/Sources/Feature/Search/ViewControllers/SearchResultViewController.swift
  Clokey/Clokey/Sources/Feature/Search/ViewControllers/SearchViewController.swift
  Clokey/Clokey/Sources/Network/history/Endpoints/HistoryEndpoint.swift
  Clokey/Clokey/Sources/Network/history/Response/HistoryResponseDTO.swift
  Clokey/Clokey/Sources/Network/history/Service/HistoryService.swift
Labels: feature

#102 [Fix] 전체적인 옷장 내 버그 수정
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Resources/Assets.xcassets/2D ICONS/dot3_icon.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/2D ICONS/dot3_icon.imageset/더보기 (3).png
  Clokey/Clokey/Resources/Assets.xcassets/2D ICONS/dot3_icon.imageset/더보기 (4).png
  Clokey/Clokey/Resources/Assets.xcassets/2D ICONS/trash_icon.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/2D ICONS/trash_icon.imageset/Vector (4).png
  Clokey/Clokey/Resources/Assets.xcassets/2D ICONS/trash_icon.imageset/trash_icon.png
  Clokey/Clokey/Resources/Assets.xcassets/2D ICONS/write_icon.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/2D ICONS/write_icon.imageset/Group.png
  Clokey/Clokey/Resources/Assets.xcassets/2D ICONS/write_icon.imageset/write_icon.png
  Clokey/Clokey/Resources/Assets.xcassets/Compoenets_icon/erase_icon.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/Compoenets_icon/erase_icon.imageset/지우기 (1).png
  Clokey/Clokey/Resources/Assets.xcassets/Compoenets_icon/erase_icon.imageset/지우기 (2).png
  Clokey/Clokey/Resources/Assets.xcassets/banner/bannerimage1.imageset/Cloth Donation.png
  Clokey/Clokey/Resources/Assets.xcassets/banner/bannerimage1.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/banner/bannerimage1.imageset/image 75.png
  Clokey/Clokey/Resources/Assets.xcassets/banner/bannerimage2.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/banner/bannerimage2.imageset/Lockers.png
  Clokey/Clokey/Resources/Assets.xcassets/banner/bannerimage2.imageset/image 74.png
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/ArrangeClosetBannerView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/ArrangeClosetViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/SmartSummationBannerView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/SmartSummationModel.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/ClosetView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/ClosetViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/ClosetPopUpView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/ClosetPopUpViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/PopUpDropdownView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/PopUpDropdownViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/DisplayAll/DisplayAllViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerCollectionViewCell.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerInfoView.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerInfoViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerModel.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/More/UpdateFriendClothesViewController.swift
Labels: bug

#104 [Fix] 신고 UI 변경 및 기능 추가 외 버그 수정
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Common/Components/Report/AccountReportCompleteViewController.swift
  Clokey/Clokey/Sources/Common/Components/Report/AccountReportViewController.swift
  Clokey/Clokey/Sources/Common/Components/Report/CustomReportCompleteView.swift
  Clokey/Clokey/Sources/Common/Components/Report/CustomReportCompleteViewController.swift
  Clokey/Clokey/Sources/Common/Components/Report/CustomReportView.swift
  Clokey/Clokey/Sources/Common/Components/Report/CustomReportViewController.swift
  Clokey/Clokey/Sources/Common/Components/Report/ReportReasonView.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/Photo/CustomGalleryViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/Photo/PhotoEditViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/CalendarDetailViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/CalendarCommentViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/FriendsActionSheetViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/FriendsCalendarDetailViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift
  Clokey/Clokey/Sources/Network/Common/Domain.swift
  Clokey/Clokey/Sources/Network/report/Endpoints/ReportEndpoint.swift
  Clokey/Clokey/Sources/Network/report/Request/ReportRequestDTO.swift
  Clokey/Clokey/Sources/Network/report/Response/ReportResponseDTO.swift
  Clokey/Clokey/Sources/Network/report/Service/ReportService.swift
  Clokey/Clokey/Supporting Files/Info.plist
Labels: bug, feature

#105 [Fix] 약관동의뷰/홈뷰/팝업뷰/Asset 파일 수정, 날씨 데이터 수정
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Resources/Assets.xcassets/2D ICONS/location_icon.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/2D ICONS/location_icon.imageset/Vector-4.png
  Clokey/Clokey/Resources/Assets.xcassets/2D ICONS/location_icon.imageset/Vector.png
  Clokey/Clokey/Resources/Assets.xcassets/private_icon.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/private_icon.imageset/Group 1707481830-2.png
  Clokey/Clokey/Resources/Assets.xcassets/private_icon.imageset/Group 1707481831.png
  Clokey/Clokey/Resources/Assets.xcassets/public_icon.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/public_icon.imageset/Group 1707481829-2.png
  Clokey/Clokey/Resources/Assets.xcassets/public_icon.imageset/Group 1707481829-4.png
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Popup/PopupView.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Popup/PopupViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Temperature/WeatherChooseViewController.swift
  Clokey/Clokey/Sources/Feature/Agreement/AgreementDetailViewController.swift
  Clokey/Clokey/Sources/Feature/Agreement/AgreementViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/More/UpdateFriendCalendarViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/More/UpdateFriendClothesViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift
  Clokey/Clokey/Sources/Feature/Home/Views/NewsViews/More/UpdateFriendCalendarView.swift
  Clokey/Clokey/Sources/Feature/Home/Views/NewsViews/More/UpdateFriendClothesView.swift
  Clokey/Clokey/Sources/Feature/Home/Views/PickViews/PickView.swift
  Clokey/Clokey/Sources/Feature/Home/Views/PickViews/Popup/PickPopUpView.swift
  Clokey/Clokey/Sources/Feature/Profile/EditProfile/CustomBottomSheetViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/EditProfile/EditProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileActionViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Services/WeatherAPI.swift
Labels: bug

#106 [Fix] 날씨 정보 불러오기 수정
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift
  Clokey/Clokey/Sources/Feature/Services/WeatherAPI.swift
Labels: bug

#107 [Bug] 전체적인 옷장 내 버그 수장 ver2
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/ArrangeClosetBannerView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/SmartSummationBannerView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/ClosetView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/ClosetViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/ClosetPopUpView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/ClosetPopUpViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerCollectionViewCell.swift
Labels: bug

#109 [Fix] 약관동의 세부페이지 및 옷 이름 글자수 제한
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddClothViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Popup/PopupView.swift
  Clokey/Clokey/Sources/Feature/Agreement/AgreementCell.swift
  Clokey/Clokey/Sources/Feature/Agreement/AgreementDetailViewController.swift
  Clokey/Clokey/Sources/Feature/Agreement/AgreementViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift
  Clokey/Clokey/Sources/Feature/Home/Views/PickViews/Popup/PickPopUpView.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift
  Clokey/Clokey/Sources/Network/home/Response/OneYearAgoHistoriesResponseDTO.swift
Labels: bug

#110 [Feature] 사용자 차단 기능 구현
  Clokey/Clokey/Sources/Common/Components/Report/CustomReportCompleteViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/CalendarCommentViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/CommentCell.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/FriendsActionSheetViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/FriendsCalendarDetailViewController.swift
  Clokey/Clokey/Sources/Network/members/Endpoints/MembersEndpoint.swift
  Clokey/Clokey/Sources/Network/members/Service/MembersService.swift
Labels: bug, feature

#112 [Bug] 경고문 제거
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Thick/ThickViewController.swift
  Clokey/Clokey/Sources/Feature/Agreement/AgreementViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/CalendarDetailViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/FriendsCalendarDetailViewController.swift
  Clokey/Clokey/Sources/Feature/Nofitication/ViewControllers/NotificationViewController.swift
  Clokey/Clokey/Sources/Feature/Search/ViewControllers/SearchResultViewController.swift
  Clokey/Clokey/Sources/Feature/Search/view/SearchView.swift
Labels: bug

#113 [Fix] 대댓글 버그 수정 및 경고문 제거
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/Photo/CustomGalleryViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/CalendarCommentView.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/CalendarCommentViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/CommentCell.swift
  Clokey/Clokey/Sources/Network/notification/Endpoints/NotificationEndpoints.swift
Labels: bug

#114 [Feat/FIX] 차단 API 추가 및 프로필 뷰 수정
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddClothViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/Main/NewsViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift
  Clokey/Clokey/Sources/Feature/Home/Views/NewsViews/Main/NewsView.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileView.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/YourFollowList/YourFollowListViewController.swift
Labels: bug, feature

#116 [Fix] 기록하기에서 사진이 뜨지 않는 버그 수정
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/Photo/CustomGalleryViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/Photo/PhotoEditViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/RecordOOTDViewController.swift
Labels: bug, hotfix

#117 [Feature] 차단목록 부분 구현, [Bug] 배너 부분 버그 수정
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Popup/PopupView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/ArrangeClosetView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/SmartSummationView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/SmartSummationViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/ClosetPopUpView.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerViewController.swift
  Clokey/Clokey/Sources/Feature/Home/Views/PickViews/Popup/PickPopUpView.swift
  Clokey/Clokey/Sources/Feature/Profile/MyFollowList/MyFollowListViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/Block/BlockUserCell.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/Block/BlockUserModel.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/Block/BlockUserViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/SettingViewController.swift
  Clokey/Clokey/Sources/Network/members/Endpoints/MembersEndpoint.swift
  Clokey/Clokey/Sources/Network/members/Response/MembersInfoResponseDTO.swift
  Clokey/Clokey/Sources/Network/members/Service/MembersService.swift
Labels: bug, feature

#122 [Fix] 프로필 달력에서 기록 체크 시, 본인 확인 기능
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/RecordOOTDView.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/RecordOOTDViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/SettingViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowCalendarViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift
  Clokey/Clokey/Sources/Network/members/Endpoints/MembersEndpoint.swift
  Clokey/Clokey/Sources/Network/members/Response/MembersInfoResponseDTO.swift
  Clokey/Clokey/Sources/Network/members/Service/MembersService.swift
  Clokey/Clokey/Sources/Network/report/Response/ReportResponseDTO.swift
Labels: bug

#124 [Fix] 회원조회 및 프로필 수정
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Common/Components/ImagePickViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddImage/LastAddViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Temperature/WeatherChooseViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Thick/ThickViewController.swift
  Clokey/Clokey/Sources/Feature/Home/Cells/UpdateFriendCalendarCollectionViewCell.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/Main/NewsViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileView.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileView.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/YourFollowList/YourFollowListViewController.swift
  Clokey/Clokey/Sources/Network/home/Response/OneYearAgoHistoriesResponseDTO.swift
  Clokey/Clokey/Sources/Network/members/Response/MembersInfoResponseDTO.swift
Labels: bug, feature

#125 [Fix] SearchViewController에서 추천검색어 클릭 검색시, 검색이 두번 되는 버그 수정 및 주석제거
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Resources/Assets.xcassets/2D ICONS/goback.imageset/Contents.json
  Clokey/Clokey/Resources/Assets.xcassets/2D ICONS/goback.imageset/goback.png
  Clokey/Clokey/Resources/Assets.xcassets/Compoenets_icon/goback.imageset/goback.png
  Clokey/Clokey/Resources/Fonts/Noto_Sans_KR/NotoSansKR-VariableFont_wght.ttf
  Clokey/Clokey/Resources/Fonts/Noto_Sans_KR/OFL.txt
  Clokey/Clokey/Resources/Fonts/Noto_Sans_KR/README.txt
  Clokey/Clokey/Resources/Fonts/Noto_Sans_KR/static/NotoSansKR-Black.ttf
  Clokey/Clokey/Resources/Fonts/Noto_Sans_KR/static/NotoSansKR-Bold.ttf
  Clokey/Clokey/Resources/Fonts/Noto_Sans_KR/static/NotoSansKR-ExtraBold.ttf
  Clokey/Clokey/Resources/Fonts/Noto_Sans_KR/static/NotoSansKR-ExtraLight.ttf
  Clokey/Clokey/Resources/Fonts/Noto_Sans_KR/static/NotoSansKR-Light.ttf
  Clokey/Clokey/Resources/Fonts/Noto_Sans_KR/static/NotoSansKR-Medium.ttf
  Clokey/Clokey/Resources/Fonts/Noto_Sans_KR/static/NotoSansKR-Regular.ttf
  Clokey/Clokey/Resources/Fonts/Noto_Sans_KR/static/NotoSansKR-SemiBold.ttf
  Clokey/Clokey/Resources/Fonts/Noto_Sans_KR/static/NotoSansKR-Thin.ttf
  Clokey/Clokey/Sources/Common/Components/CustomSearchField.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Temperature/WeatherChooseViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/CalendarDetailViewController.swift
  Clokey/Clokey/Sources/Feature/Main/HeaderView.swift
  Clokey/Clokey/Sources/Feature/Nofitication/Model/NotificationViewModel.swift
  Clokey/Clokey/Sources/Feature/Nofitication/VIews/NotificationCell.swift
  Clokey/Clokey/Sources/Feature/Nofitication/VIews/NotificationView.swift
  Clokey/Clokey/Sources/Feature/Nofitication/ViewControllers/NotificationViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/LikeHistory/LikeHistoryView.swift
  Clokey/Clokey/Sources/Feature/Search/ViewControllers/SearchResultViewController.swift
  Clokey/Clokey/Sources/Feature/Search/ViewControllers/SearchViewController.swift
  Clokey/Clokey/Sources/Feature/Search/view/SearchResultView.swift
  Clokey/Clokey/Sources/Feature/Search/view/SearchView.swift
  Clokey/Clokey/Sources/Network/notification/Endpoints/NotificationEndpoints.swift
  Clokey/Clokey/Supporting Files/Info.plist
Labels: bug

#128 [Fix] 옷 사진 추가 버그 수정 및 페이징 처리 수정
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddImage/LastAddViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/More/UpdateFriendCalendarViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/More/UpdateFriendClothesViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/EditProfile/EditProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/MyFollowList/MyFollowListViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/YourFollowList/YourFollowListViewController.swift
Labels: bug

#129 [Bug] 3.20 회의 때 나온옷장 관련 버그 수정
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Popup/PopupView.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Popup/PopupViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/ClosetViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/ClosetPopUpView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/ClosetPopUpViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/PopUpDropdownViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/DisplayAll/DisplayAllViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerEditViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/FolderDropdownViewController.swift
  Clokey/Clokey/Sources/Feature/Home/Views/PickViews/Popup/PickPopUpView.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift
Labels: bug

#131 [Fix] 차단 프로필 뷰 수정
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift
Labels: bug

#134 [Fix] 옷장 내 네트워크 오류 처리
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/ArrangeClosetViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/SmartSummationViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetMain/ClosetViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/ClosetPopUpViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/PopUpDropdownViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/DisplayAll/DisplayAllViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerEditViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerInfoViewController.swift
  Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerViewController.swift
Labels: hotfix

#135 [Fix] 네트워크 에러 alert 처리 및 추가 버그 수정
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddClothViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddImage/LastAddViewController.swift
  Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Popup/PopupViewController.swift
  Clokey/Clokey/Sources/Feature/AddProfile/AddProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Agreement/AgreementViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/Photo/CustomGalleryViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/RecordOOTDViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/TagCloth/TagClothViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/Calendar/CalendarViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/CalendarDetailViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/CalendarCommentViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/CustomActionSheetViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/FriendsCalendarDetailViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/LikeUser/LikeListViewController.swift
  Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/LikeUser/LikeUserCell.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/PopUpDropdownViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/Main/NewsViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/More/UpdateFriendCalendarViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/More/UpdateFriendClothesViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift
  Clokey/Clokey/Sources/Feature/Login/LoginViewController.swift
  Clokey/Clokey/Sources/Feature/Nofitication/Model/NotificationViewModel.swift
  Clokey/Clokey/Sources/Feature/Nofitication/ViewControllers/NotificationViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/EditProfile/EditProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/MyFollowList/MyFollowListViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/MyFollowList/MyFollowerUserCell.swift
  Clokey/Clokey/Sources/Feature/Profile/MyFollowList/MyFollowingUserCell.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/Block/BlockUserViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/CommentHistoryView.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/CommentHistoryViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/LikeHistory/LikeHistoryViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Settings/SettingViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowCalendarViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/YourFollowList/YourFollowListViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/YourFollowList/YourFollowerUserCell.swift
  Clokey/Clokey/Sources/Feature/Profile/YourFollowList/YourFollowingUserCell.swift
  Clokey/Clokey/Sources/Feature/Search/ViewControllers/SearchResultViewController.swift
  Clokey/Clokey/Sources/Feature/Search/ViewControllers/SearchViewController.swift
Labels: bug

#138 fix: 팝업창 폰트 크기 및 텍스트 상이한 거 수정
  Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/ClosetPopUpView.swift
  Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/ClosetPopUpViewController.swift
Labels: bug

#139 [Fix] 홈, 프로필 버그 수정
  Clokey/Clokey.xcodeproj/project.pbxproj
  Clokey/Clokey/Sources/Feature/AddProfile/AddProfileView.swift
  Clokey/Clokey/Sources/Feature/AddProfile/AddProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Agreement/AgreementViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/Main/NewsViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/More/UpdateFriendCalendarViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/More/UpdateFriendClothesViewController.swift
  Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift
  Clokey/Clokey/Sources/Feature/Home/Views/NewsViews/Main/NewsView.swift
  Clokey/Clokey/Sources/Feature/Home/Views/NewsViews/More/UpdateFriendCalendarView.swift
  Clokey/Clokey/Sources/Feature/Home/Views/NewsViews/More/UpdateFriendClothesView.swift
  Clokey/Clokey/Sources/Feature/Login/LoginViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/EditProfile/EditProfileView.swift
  Clokey/Clokey/Sources/Feature/Profile/EditProfile/EditProfileViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/My/ProfileView.swift
  Clokey/Clokey/Sources/Feature/Profile/MyFollowList/MyFollowListViewController.swift
  Clokey/Clokey/Sources/Feature/Profile/MyFollowList/MyFollowerUserCell.swift
  Clokey/Clokey/Sources/Feature/Profile/MyFollowList/MyFollowingUserCell.swift
  Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileView.swift
Labels: bug
